### ISSUE TITLE
Don't use `use lib 'lib'` in installable code

### ISSUE THREAD

**Issue by ugexe** [Kaiepi/p6-PSBot#10]
https://github.com/Kaiepi/p6-PSBot/blob/ca3d9bd179e0e11b096d1daae785e7c13b4c2d45/bin/psbot#L3
How do you expect this to act if it gets installed? Unlike tests, bin/scripts are installed and thus cannot assume to know the type of repositories being used or their filesystem structure (which may change at installation time).

**Comment by Kaiepi** [comment]
This has been fixed since https://github.com/Kaiepi/p6-PSBot/commit/cdab65bb7f1ce06a6a48d847dd2dc7c3fbb2ded1
